* plans
** week 1: introduction
*** introductions, 15
- your name, program, pronouns, last thing you watched in transit

*** syllabus review, 20 
2 main goals of the course:
- traditional ML education:
  - learn the most important algorithms (linear, logistic, also unsupervised)
  - learn some principles about model architecture
- less traditional:
  - examine the most current ML research for common issues.
  - problems with bias, automation, sustainability, dataset curation,
    etc.
  - considering the ways that coding tools provide much of the
    algorithmic knowledge, this expertise with critical skills will
    give you an edge when applying for ML jobs, or when using ML tools
    in your job.

The main assignment of the course is actually a paper, a conference
paper. Requires you to know and respond to the most current research. 

*** HAI article, 40-45
- Read the article & answer prompts, 15 minutes
  - 10 minutes read, 5 minutes answer
  - prompts for reading:
    - In your understanding, why do these automated processes
      discriminate, what causes them to discriminate? Try to narrow down
      the root cause.
    - Do you perceive any potential oversights or flaws in the authors'
      arguments? Is there anything that should be interrogated or
      explored in more depth?
- Discuss in small groups, 10 minutes.
  - introduce yourself to your group
- Discuss as large group, 15 minutes
  - root cause: that increasing scale brings in all kinds of problems.
    The common denomenator.q
  - oversight: that if you apply to a lot of jobs, you're maybe using a
    similar application, which is not tailored and may be rejected for
    not being a good fit.
  
*** break
*** python challenge, 30 
Write some python code that contains the following components below.
Use a blank sheet of paper to code.

Required:
- a loop
- a list
- a function

One solution:
#+begin_src python
  import random
  def greeting(name):
      greetings = [
	  "how are you doing today?",
	  "what's up?",
	  "como te sientes?",
	  "what's shakin'?",
	  "tudo bem?"
      ]
      print(f"Hello {name}, {random.choice(greetings)}")

  greeting('Filipa')
#+end_src

#+begin_src python
  Hello Filipa, como te sientes?
#+end_src
*** share, 20-30
*** python refresher (if time)
- data types
- variables
- list indexing, slicing
- loops
- logic
- functions
- dictionaries
- libraries

** week 2: data & bias
*** cleaning a dataset
- how to create a virtual environment
- exploring a dataset
- decide what you want to predict
- cleaning the dataset accordingly 

**** create virtual environment for ml packages 5-10
#+begin_src console
  # make a new folder for our work
  cd Desktop
  mkdir 656-notebooks
  
  # create and activate the environment
  conda create --name ml-env pandas scikit-learn ipykernel
  conda activate ml-env

  # now add the kernel to use on Jupyter
  ipython kernel install --user --name=ml-env
#+end_src

Your conda environment will be installed in

~/Users/fcalado/.conda/envs/ml-env/bin/python~

Your kernel will be installed at:

~/Users/fcalado/Library/Jupyter/kernels/ml-env~

**** access dataset
https://bit.ly/lgbtq-legislation-2025

Go to the sheet, navigate to the "Anti-LGBTQ Bills", download as csv.

**** preliminary exploration 5-10 

#+begin_src python

  import pandas as pd

  df = pd.read_csv("2025-bills.csv")

  df.shape
  df.info()
  df.head()
  df.columns
  df['State']
  df.value_counts('State')
  df.value_counts('Bill_Type')
#+end_src

**** GROUPS: close reading dataset in groups, 20-30 minutes
- pass out the printout
- what kind of predictions could we make from the data? 10 min
  - think about which of these columns can be used to guess about
    another column.
    - Example:
    - what states are likely to have "Worst" risk?
- share 20 min
- how to label a bill based on its summary and notes.
  - Summary + Notes = Bill Type
  - other things which could be interesting, but we won't pursue (for
    now):
    - Sponsors - are there any patterns in who is sponsoring certain
      bills?
    - State - are there patterns in which states have certain bill
      types? or how many bills per state?
- the decisions we make about prediction will affect the way we clean
  and process the dataset.
- for looking at "worst" we might want to create a new dataframe of
  just worst bills for Youth State Risk. 
#+begin_src python
  worst = df['Youth State Risk'] == 'Worst'
#+end_src
**** cleaning
- we are looking to predict bill type based on summary and notes
- we need three columns: summary, notes, bill type
  - spend a couple of minutes looking at the column. Check for
    inconsistencies, things we'd want to standardize or regularize. 
  - what do we need to clean from each column, if at all?

We can also use pandas to do this programmatically. What are the most
frequent values for this column?

#+begin_src python
  df["Bill Type"].value_counts()
#+end_src

There are 298 different labels. That's because we have examples like
the one below. 

#+begin_quote
"DEI Ban"
"DEI Ban "
" DEI Ban"
"DEI Ban  "
#+end_quote

So we decide that we want to cut down the inconsistent labels. First,
preserve the original.

#+begin_src python
  df["Bill Type Raw"] = df["Bill Type"]
#+end_src

Second, let's split up the long string into individual ones.

#+begin_src python
  df["Bill Type"].str.split("/")
#+end_src

Third, create a new column for the split labels. 

#+begin_src python
df["bill_type_labels"] = df["Bill Type"].str.split("/").fillna("")
#+end_src

Fourth, strip() to remove white spaces.

#+begin_src python
  def clean_labels(labels):
    return [label.strip() for label in labels]

  df["bill_type_labels"] = df["bill_type_labels"].apply(clean_labels)
#+end_src

Make the difference between these two columns visible.

#+begin_src python
print(df["Bill Type Raw"].iloc[0])
print(df["bill_type_labels"].iloc[0])
#+end_src

Fifth, pull out the individual label, use ~explode()~

#+begin_src python
  labels = df["bill_type_labels"].explode()
#+end_src

We can ask how many times each label is used!

#+begin_src python
  labels.value_counts()
  labels.unique()
  # see the comparison between the original and our new categories.
  len(labels.unique())
  len(df['Bill Type Raw'].unique())
#+end_src

Are there any other cleaning steps we'd want to do?
- remove labels that appear 1 time? less than 3 times?

**** final step — MultiLabelBinarizer
To train a classifier, we would create a "sparse" matrix. A sparse
matrix has 0s and 1s to indicate the presence of a category.

We will use the library ~sklearn~.

#+begin_src python
  from sklearn.preprocessing import MultiLabelBinarizer

  mlb = MultiLabelBinarizer()

  Y = mlb.fit_transform(df["bill_type_labels"])
#+end_src

This creates an ~mlb~ object and ~Y~ object. The first contains our
classes, and the second is our matrix.

#+begin_src python

  # all of our unique labels
  mlb.classes_

  # scary matrix...
  Y

  # see that we have the same number of rows as bills
  # and we have the same number of columns as labels!!
  Y.shape()

#+end_src

**** our workflow

RAW BILL TYPE ->

Preserve original ->

Split on "/" ->

Create new column with no NANs ->

Clean whitespace ->

MultiLabelBinarizer ->

0 / 1 matrix

*** break
*** provocations sharing 30 minutes
- in partners, share your provocations. 5 minutes.
- share out with the class. 10 minutes. 
*** continue cleaning
*** start homework
** week 3: linear regression
- intuit linear regression
- hypothesis, loss, gradient descent
- practice with sci-kit learn
- break
- intuit logistic regression
- practice with sci-kit learn
- time to practice on own datasets

*** Overview of Linear Regression

**** "linear" relationships
What is the relationship between the three columns, going row by row?
What is the pattern hidden in each row?

| a  | b  |  c |
|----+----+----|
|  4 |  2 |  8 |
|  1 |  2 |  5 |
|  0 |  5 | 10 |
|  2 |  1 |  4 |

a*2 + b = c

This is what's called a linear relationship.

**** "supervised learning"
When the data is labeled in some way. We will see examples of learning
where the data is not labeled at all, next week. 

**** defintion
Linear Regression is a supervised learning algorithm that predicts
continuous values based on one or more input variables. It fits a
straight line that best represents the data.

The goal of linear regression is to find a straight line that
/minimizes the error/ (the difference) between the observed data
points and the predicted values. This line helps us predict the
dependent variable for new, unseen data.

**** graphing linear regresssion

Housing example:
- you have a dataset of house size and their prices.
- the larger the house, the higher the price
- linear regression wants to find the line that cuts through the
  most points as possible
- the size of the houses is the X
  - input variable
- the price is the Y
  - target variable -> what we want to predict
- (x, y) is a single training example

**** 3 formulas under the hood
You want Y to represent a straight line.
- What is the formula for a line?
- w,b are coefficients, parameters. 

#+begin_src
  Y = mx + b

  or,

  f(x) = wx + b
#+end_src

Some intuition:
- f(x) = 0*x + 1.5
  - w = 0, b = 1.5
  - the line starts at y = 1.5 and runs horizontal (flat) across the x
    axis)
- f(x) = 0.5*x + 0
  - w = .5 (which is really .5/1)
  - b = 0
- f(x) = .5*x + 1
  - is actually the same line as above, but starts at 1

**The goal, as you can see above, is to have right values for w,b so
that you can fit a straight line best through the data.**

So how do you find these values for w,b?
- we need to measure how well our line fits our data.
- you start with the cost function:
  - measures the error between our prediction and the actual value
  - MSE - mean squared error (squared to get rid of negatives)

#+begin_src
  (y(hat) - y^i)^2
#+end_src

The cost function takes J as its variable.
- you want to get the smallest J possible.
- you want to minimize the error bewteen the prediction and the actual
  value.
- the J graph is actually a parabola -- there is a lowest point for J,
  and that is what we want.
  - we input differnt values of w until we get the lowest value for J.
  - see Andrew Ng, #12 Machine Learning Specialization [Course 1, Week
    1, Lesson 3]

But how do we know what values to pick for w that will minimize J?
- you use the gradient descent algorithm
- gradient descent finds where to minimize w.
  - the formula takes current w and updates it by subtracting a
    "derivative" of w from w.

#+begin_src
  w = w - derivative of w
#+end_src
    
Once you get the lowest possible value for w, then you plug it back
into the line function, and you're done!

*** scikit learn

**** loading, prepping data
#+begin_quote console

conda activate 656-ml
conda install matplotlib seaborn

#+end_quote

Importing libraries, loading data

#+begin_src python
  # Import libraries.
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import seaborn as sns

  # Let's use the well-known California housing dataset.

  # Read in California housing dataset.
  from sklearn.datasets import fetch_california_housing


  housing = fetch_california_housing()
#+end_src

Preparing the data
- Let's split the data into training and testing sets.
- We import the train_test_split() method from
  sklearn.model_selection, then invoke it, specifying a test set
  percentage, and a random_state.
- We'll also use simple linear regression, using the feature
  corresponding to the average number of rooms.

#+begin_src python
  # Import train_test_split.
  from sklearn.model_selection import train_test_split


  # Create features X and target y.
  X = pd.DataFrame(housing.data, columns=housing.feature_names)[["AveRooms"]]
  y = housing.target  # Median house value in $100,000s


  # Split the dataset into training (80%) and testing (20%) sets.
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  # Examine our training data

  X_train
#+end_src

Now that we've split the data into test and train sets, let's
standardize features. This process ensures that all variables are on
the same scale, which can improve model performance and numerical
stability.

#+begin_src python
# Import StandardScaler.
from sklearn.preprocessing import StandardScaler

# Instantiate StandardScaler.
scaler = StandardScaler()

# Fit and transform training data.
X_train_scaled = scaler.fit_transform(X_train)

# Also transform test data.
X_test_scaled = scaler.transform(X_test)
#+end_src

In this code, StandardScaler is a data preprocessing tool used to
remove the mean and scale features to unit variance. This helps
prevent certain features from dominating the model due to differences
in scale.
- Compare X_train with X_train_scaled to see the difference.

**** training the model
Now, we will train the linear regression model
- To create a linear regression model, import LinearRegression() from
  sklearn.linear_model. Invoke it and assign it to a variable.

#+begin_src python
  # Import LinearRegression.
  from sklearn.linear_model import LinearRegression


  # Instantiate linear regression model.
  model = LinearRegression()

  # Fit the model to the training data.
  model.fit(X_train_scaled, y_train)
#+end_src

See coefficients:
- this is the weight, the "w", which is multiplied by all of the
  inputs in the x column.
  
#+begin_src python
  model.coef_
#+end_src
 
Making predictions
- Now that we've trained our model, we make predictions on the test
  set.

#+begin_src python
  # Make predictions on the testing data.
  y_pred = model.predict(X_test_scaled)

  # see our predictions
  y_pred
#+end_src

**** evaluating performance
Now that we've made predictions on the test set, we need to know how
well they match with reality. There are several metrics available to
evaluate the performance of a regression algorithm. Some of the most
common ones are the coefficient of determination (R2), mean squared
error (MSE), and root mean squared error (RMSE).

The coefficient of determination, denoted R2, measures how well a
regression model explains the variability of the target variable. In
other words, it quantifies how much of the variability in the target
variable is explained by the predictors, known as the goodness of fit.

How do we interpret R2?

    R2 = 1: the model perfectly explains all the variance in the
    target variable.
    
    R2 = 0: the model explains none of the variance; predictions are
    no better than simply using the mean.
    
    R2 < 0: The model performs worse than simply using the mean,
    indicating a poor fit.
    
#+begin_src python
  # Import metrics.
  from sklearn.metrics import mean_squared_error, r2_score


  # Calculate and print R^2 score.
  r2 = r2_score(y_test, y_pred)
  print(f"R-squared: {r2:.4f}")
#+end_src

MSE calculates the average squared difference between actual and
predicted values.

#+begin_src python
  # Calculate and print MSE.
  mse = mean_squared_error(y_test, y_pred)
  print(f"Mean squared error: {mse:.4f}")
#+end_src

**** multiple linear regression

Let's rerun the model using all of our available features, not just
the average number of rooms. Do you expect better or worse results?

#+begin_src python
  # Uses all features.
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import seaborn as sns
  from sklearn.datasets import fetch_california_housing
  from sklearn.model_selection import train_test_split
  from sklearn.preprocessing import StandardScaler
  from sklearn.linear_model import LinearRegression
  from sklearn.metrics import mean_squared_error, r2_score


  # Load data set.
  housing = fetch_california_housing()


  # Split into X, y.
  X = pd.DataFrame(housing.data, columns=housing.feature_names)
  y = housing.target  # Median house value in $100,000s
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


  # Scale the data.
  scaler = StandardScaler()


  X_train_scaled = scaler.fit_transform(X_train)
  X_test_scaled = scaler.transform(X_test)


  # Create model and fit it to the training data.
  model = LinearRegression()
  model.fit(X_train_scaled, y_train)


  # Make predictions.
  y_pred = model.predict(X_test_scaled)


  # Calculate and print errors.
  r2 = r2_score(y_test, y_pred)
  print(f"R-squared: {r2:.4f}")


  mse = mean_squared_error(y_test, y_pred)
  print(f"Mean squared error: {mse:.4f}")


  rmse = mse ** 0.5
  print(f"Root mean squared error: {rmse:.4f}")
#+end_src

We see the results are quite a bit better than when using only one
feature. However, this raises the question of whether we need all the
features. Are some features more relevant than others? Choosing the
most relevant features from the dataset is known as feature selection.

Feature selection is important for a number of reasons.
- Improves accuracy. Removing irrelevant or redundant features helps
  the model focus on meaningful patterns.
- Speeds up training. Reducing the number of features decreases
  computational time and memory usage.

*** break
*** logistic regression
- wants to predict categories, classes, categorical values.


*** notes

Linear regression formula:

y(w,x) = w0 + w1x1 + ... + wpxp

Ordinary Least Squares

** week 4: clustering
